name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write # to fetch code (actions/checkout)

jobs:
  QA:
    name: Quality Assurance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup ASDF VM
        # TODO: use @v4 when released https://github.com/asdf-vm/actions/issues/594
        uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302
        with:
          asdf_version: 0.16.7
      - name: tools 
        run: just tools
        shell: bash
      - name: qa
        run: just qa
        shell: bash
      - name: Check if there are any uncommitted changes
        run: |
          git diff
        shell: bash
      - name: unittest
        run: just unittest
        shell: bash
