name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write # to fetch code (actions/checkout)

jobs:
  QA:
    name: Quality Assurance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install asdf
        uses: asdf-vm/actions/install@v4
      - name: tools 
        run: just tools
        shell: bash
      - name: qa
        run: just qa
        shell: bash
      - name: Check if there are any uncommitted changes
        run: |
          git diff --exit-code
        shell: bash
      - name: unittest
        run: just unittest
        shell: bash
