name: publish
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # to fetch code (actions/checkout)

jobs:
  Publish:
    name: Publish package to golang proxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup ASDF VM
        uses: asdf-vm/actions/install@v4
        with:
          asdf_version: 0.17.0
      - name: tools 
        run: just tools
        shell: bash
      - name: qa
        run: just qa
        shell: bash
      - name: Check if there are any uncommitted changes
        run: |
          git diff
        shell: bash
      - name: unittest
        run: just unittest
        shell: bash
      - name: publish
        run: just publish
        shell: bash
